[package]
name = "kittypaws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "paws"
path = "src/main.rs"

[workspace]
members = [
    "plugins/deathloop",
]

[dependencies]
libloading = "0.5"
config = "0.13.1"
pyo3 = {"version" = "0.17.3", features = ["auto-initialize"]}
tokio = { version = "1", features = ["full"] }
